export type Question = {
  id: number;
  text: string;
  factor: 'Extraversion' | 'Agreeableness' | 'Conscientiousness' | 'Emotional Stability' | 'Intellect';
  keyed: 'plus' | 'minus';
};

export const oceanQuestions: Question[] = [
  { id: 1, text: "Am the life of the party.", factor: 'Extraversion', keyed: 'plus' },
  { id: 2, text: "Feel little concern for others.", factor: 'Agreeableness', keyed: 'minus' },
  { id: 3, text: "Am always prepared.", factor: 'Conscientiousness', keyed: 'plus' },
  { id: 4, text: "Get stressed out easily.", factor: 'Emotional Stability', keyed: 'minus' },
  { id: 5, text: "Have a rich vocabulary.", factor: 'Intellect', keyed: 'plus' },
  { id: 6, text: "Don't talk a lot.", factor: 'Extraversion', keyed: 'minus' },
  { id: 7, text: "Am interested in people.", factor: 'Agreeableness', keyed: 'plus' },
  { id: 8, text: "Leave my belongings around.", factor: 'Conscientiousness', keyed: 'minus' },
  { id: 9, text: "Am relaxed most of the time.", factor: 'Emotional Stability', keyed: 'plus' },
  { id: 10, text: "Have difficulty understanding abstract ideas.", factor: 'Intellect', keyed: 'minus' },
  { id: 11, text: "Feel comfortable around people.", factor: 'Extraversion', keyed: 'plus' },
  { id: 12, text: "Insult people.", factor: 'Agreeableness', keyed: 'minus' },
  { id: 13, text: "Pay attention to details.", factor: 'Conscientiousness', keyed: 'plus' },
  { id: 14, text: "Worry about things.", factor: 'Emotional Stability', keyed: 'minus' },
  { id: 15, text: "Have a vivid imagination.", factor: 'Intellect', keyed: 'plus' },
  { id: 16, text: "Keep in the background.", factor: 'Extraversion', keyed: 'minus' },
  { id: 17, text: "Sympathize with others' feelings.", factor: 'Agreeableness', keyed: 'plus' },
  { id: 18, text: "Make a mess of things.", factor: 'Conscientiousness', keyed: 'minus' },
  { id: 19, text: "Seldom feel blue.", factor: 'Emotional Stability', keyed: 'plus' },
  { id: 20, text: "Am not interested in abstract ideas.", factor: 'Intellect', keyed: 'minus' },
  { id: 21, text: "Start conversations.", factor: 'Extraversion', keyed: 'plus' },
  { id: 22, text: "Am not interested in other people's problems.", factor: 'Agreeableness', keyed: 'minus' },
  { id: 23, text: "Get chores done right away.", factor: 'Conscientiousness', keyed: 'plus' },
  { id: 24, text: "Am easily disturbed.", factor: 'Emotional Stability', keyed: 'minus' },
  { id: 25, text: "Have excellent ideas.", factor: 'Intellect', keyed: 'plus' },
  { id: 26, text: "Have little to say.", factor: 'Extraversion', keyed: 'minus' },
  { id: 27, text: "Have a soft heart.", factor: 'Agreeableness', keyed: 'plus' },
  { id: 28, text: "Often forget to put things back in their proper place.", factor: 'Conscientiousness', keyed: 'minus' },
  { id: 29, text: "Get upset easily.", factor: 'Emotional Stability', keyed: 'minus' },
  { id: 30, text: "Do not have a good imagination.", factor: 'Intellect', keyed: 'minus' },
  { id: 31, text: "Talk to a lot of different people at parties.", factor: 'Extraversion', keyed: 'plus' },
  { id: 32, text: "Am not really interested in others.", factor: 'Agreeableness', keyed: 'minus' },
  { id: 33, text: "Like order.", factor: 'Conscientiousness', keyed: 'plus' },
  { id: 34, text: "Change my mood a lot.", factor: 'Emotional Stability', keyed: 'minus' },
  { id: 35, text: "Am quick to understand things.", factor: 'Intellect', keyed: 'plus' },
  { id: 36, text: "Don't like to draw attention to myself.", factor: 'Extraversion', keyed: 'minus' },
  { id: 37, text: "Take time out for others.", factor: 'Agreeableness', keyed: 'plus' },
  { id: 38, text: "Shirk my duties.", factor: 'Conscientiousness', keyed: 'minus' },
  { id: 39, text: "Have frequent mood swings.", factor: 'Emotional Stability', keyed: 'minus' },
  { id: 40, text: "Use difficult words.", factor: 'Intellect', keyed: 'plus' },
  { id: 41, text: "Don't mind being the center of attention.", factor: 'Extraversion', keyed: 'plus' },
  { id: 42, text: "Feel others' emotions.", factor: 'Agreeableness', keyed: 'plus' },
  { id: 43, text: "Follow a schedule.", factor: 'Conscientiousness', keyed: 'plus' },
  { id: 44, text: "Get irritated easily.", factor: 'Emotional Stability', keyed: 'minus' },
  { id: 45, text: "Spend time reflecting on things.", factor: 'Intellect', keyed: 'plus' },
  { id: 46, text: "Am quiet around strangers.", factor: 'Extraversion', keyed: 'minus' },
  { id: 47, text: "Make people feel at ease.", factor: 'Agreeableness', keyed: 'plus' },
  { id: 48, text: "Am exacting in my work.", factor: 'Conscientiousness', keyed: 'plus' },
  { id: 49, text: "Often feel blue.", factor: 'Emotional Stability', keyed: 'minus' },
  { id: 50, text: "Am full of ideas.", factor: 'Intellect', keyed: 'plus' },
];
