export type PanasQuestion = {
  id: number;
  text: string;
  scales: string[]; // Items can belong to multiple scales
};

// Official PANAS-X 60-Item Map
export const panasQuestions: PanasQuestion[] = [
  { id: 1, text: "cheerful", scales: ["Joviality"] },
  { id: 2, text: "disgusted", scales: ["Hostility"] },
  { id: 3, text: "attentive", scales: ["Positive Affect", "Attentiveness"] },
  { id: 4, text: "bashful", scales: ["Shyness"] },
  { id: 5, text: "sluggish", scales: ["Fatigue"] },
  { id: 6, text: "daring", scales: ["Self-Assurance"] },
  { id: 7, text: "surprised", scales: ["Surprise"] },
  { id: 8, text: "strong", scales: ["Positive Affect", "Self-Assurance"] },
  { id: 9, text: "scornful", scales: ["Hostility"] },
  { id: 10, text: "relaxed", scales: ["Serenity"] },
  { id: 11, text: "irritable", scales: ["Negative Affect", "Hostility"] },
  { id: 12, text: "delighted", scales: ["Joviality"] },
  { id: 13, text: "inspired", scales: ["Positive Affect"] },
  { id: 14, text: "fearless", scales: ["Self-Assurance"] },
  { id: 15, text: "disgusted with self", scales: ["Guilt"] },
  { id: 16, text: "sad", scales: ["Sadness"] },
  { id: 17, text: "calm", scales: ["Serenity"] },
  { id: 18, text: "afraid", scales: ["Negative Affect", "Fear"] },
  { id: 19, text: "tired", scales: ["Fatigue"] },
  { id: 20, text: "amazed", scales: ["Surprise"] },
  { id: 21, text: "shaky", scales: ["Fear"] },
  { id: 22, text: "happy", scales: ["Joviality"] },
  { id: 23, text: "timid", scales: ["Shyness"] },
  { id: 24, text: "alone", scales: ["Sadness"] },
  { id: 25, text: "alert", scales: ["Positive Affect", "Attentiveness"] },
  { id: 26, text: "upset", scales: ["Negative Affect"] },
  { id: 27, text: "angry", scales: ["Hostility"] },
  { id: 28, text: "bold", scales: ["Self-Assurance"] },
  { id: 29, text: "blue", scales: ["Sadness"] },
  { id: 30, text: "shy", scales: ["Shyness"] },
  { id: 31, text: "active", scales: ["Positive Affect"] },
  { id: 32, text: "guilty", scales: ["Negative Affect", "Guilt"] },
  { id: 33, text: "joyful", scales: ["Joviality"] },
  { id: 34, text: "nervous", scales: ["Negative Affect", "Fear"] },
  { id: 35, text: "lonely", scales: ["Sadness"] },
  { id: 36, text: "sleepy", scales: ["Fatigue"] },
  { id: 37, text: "excited", scales: ["Positive Affect", "Joviality"] },
  { id: 38, text: "hostile", scales: ["Negative Affect", "Hostility"] },
  { id: 39, text: "proud", scales: ["Positive Affect", "Self-Assurance"] },
  { id: 40, text: "jittery", scales: ["Negative Affect", "Fear"] },
  { id: 41, text: "lively", scales: ["Joviality"] },
  { id: 42, text: "ashamed", scales: ["Negative Affect", "Guilt"] },
  { id: 43, text: "at ease", scales: ["Serenity"] },
  { id: 44, text: "scared", scales: ["Negative Affect", "Fear"] },
  { id: 45, text: "drowsy", scales: ["Fatigue"] },
  { id: 46, text: "angry at self", scales: ["Guilt"] },
  { id: 47, text: "enthusiastic", scales: ["Positive Affect", "Joviality"] },
  { id: 48, text: "downhearted", scales: ["Sadness"] },
  { id: 49, text: "sheepish", scales: ["Shyness"] },
  { id: 50, text: "distressed", scales: ["Negative Affect"] },
  { id: 51, text: "blameworthy", scales: ["Guilt"] },
  { id: 52, text: "determined", scales: ["Positive Affect", "Attentiveness"] },
  { id: 53, text: "frightened", scales: ["Fear"] },
  { id: 54, text: "astonished", scales: ["Surprise"] },
  { id: 55, text: "interested", scales: ["Positive Affect"] },
  { id: 56, text: "loathing", scales: ["Hostility"] },
  { id: 57, text: "confident", scales: ["Self-Assurance"] },
  { id: 58, text: "energetic", scales: ["Joviality"] },
  { id: 59, text: "concentrating", scales: ["Attentiveness"] },
  { id: 60, text: "dissatisfied with self", scales: ["Guilt"] },
];
